chargen/urls.py
from django.urls import path

from . import views

app_name = "chargen"

urlpatterns = [
    path("random", views.generate_character, name="generate_character"),
    path("choice", views.generate_with_background, name="generate_with_background"),
]

electrumarchive/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import TemplateView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", TemplateView.as_view(template_name="index.html"), name="index"),
    path("chargen/", include("chargen.urls")),
    path("gametables/", include("gamelogic.urls")),
]

gamelogic/urls.py
from django.urls import path

from . import views

app_name = "gamelogic"

urlpatterns = [
    path("astromancies", views.astromancies_view, name="astromancies"),
    path("artifacts", views.artifacts_view, name="artifacts"),
    path("psionics", views.psionics_view, name="psionics"),
]

chargen/models.py
from django.db import models

# Create your models here.

chargen/forms.py
from django import forms
from gamelogic.backgrounds import backgrounds
from crispy_forms.helper import FormHelper
from crispy_forms.layout import Submit, Layout


class BackgroundForm(forms.Form):
    choices = [(b, b) for b in backgrounds]
    background = forms.ChoiceField(choices=choices)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.helper = FormHelper()
        self.helper.form_method = "post"

        self.helper.form_action = "chargen:generate_with_background"

        self.helper.add_input(
            Submit(
                "submit",
                "Generate",
                css_class="m-1 btn-secondary",
            )
        )

chargen/views.py
from django.shortcuts import render
from .character import Character
from .forms import BackgroundForm

# Create your views here.


def generate_character(request, background=None):
    return render(
        request,
        template_name="chargen/generate_character.html",
        context={"char": Character(background)},
    )


def generate_with_background(request):
    form = BackgroundForm(request.POST or None)
    if request.method == "POST":
        if form.is_valid():
            background = form.cleaned_data["background"]
            return generate_character(request, background)
    return render(
        request,
        template_name="chargen/generate_with_background.html",
        context={"form": form},
    )

gamelogic/views.py
from django.shortcuts import render
from .astromancies import astromancies
from .artifacts import artifacts
from .psionics import psionics

# Create your views here.


def astromancies_view(request):
    template_name = "gamelogic/d66_tables.html"
    context = {"table": astromancies, "h1": "Astromancies"}
    return render(request, template_name, context)


def artifacts_view(request):
    template_name = "gamelogic/d66_tables.html"
    context = {"table": artifacts, "h1": "Artifacts"}
    return render(request, template_name, context)


def psionics_view(request):
    template_name = "gamelogic/d66_tables.html"
    context = {"table": psionics, "h1": "Psionics"}
    return render(request, template_name, context)

chargen/templates/chargen/generate_character.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Monolith - Character Gen{% endblock title %}
{% block content %}
<h1>A Monolith Character</h1>

<div class="card">
  <div class="card-body">
    <h5 class="card-title">{{char.first_name}} {{char.last_name}}</h5>
    <h6 class="card-subtitle mb-2 text-muted">{{char.background}}</h6>
    <p>{{char.profile|safe}}</p>
    <div class="row">
        <div class="col">
            <table class="table">
            <tr>
                <th>STR</th>
                <th>DEX</th>
                <th>WIL</th>
                <th>HP</th>
            </tr>
            <tr>
                <td>{{char.STR}}</td>
                <td>{{char.DEX}}</td>
                <td>{{char.WIL}}</td>
                <td>{{char.HP}}</td>
            </tr>
            </table>
            <table class="table">
                <tr>
                    <th>{{char.dossier_name}}</th><td>{{char.dossier_option|safe}}</td>
                </tr>
                <tr>
                    <th>{{char.dossier_subpart_name}}</th>
                    <td>{{char.dossier_subpart_option|safe}}</td>
                </tr>
                <tr>
                    <th>{{char.dossier_question}}</th><td>{{char.dossier_answer|safe}}</td>
                </tr>
                <tr>
                    <th>Vice</th>
                    <td>{{char.vice}}</td>
                </tr>
            </table>
        </div>
        <div class="col">
            <table class="table">
                <thead>
                    <tr>
                        <th scope="col" colspan="2">Finishing touches</th>
                    </tr>
                </thead>
                {% for key, value in char.finishing_touches.items %}
                    <tr>
                        <th>{{key|title}}</th>
                        <td>{{value}}</td>
                    </tr>
                {% endfor %}
                    <tr>
                        <th>Starting gear</th>
                        <td>
                            <ul>
                            {% for item in char.gear %}<li>{{item|safe}}</li>{% endfor %}
                            {% for item in char.common_gear %}<li>{{item|safe}}</li>{% endfor %}
                            </ul>
                        </td>
                    </tr>
            </table>
        </div><!--col-->
    </div><!-- row-->
  </div>
</div>

{% endblock content %}

chargen/templates/chargen/generate_with_background.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}Monolith - Character Gen{% endblock title %}
{% block content %}

<h1>Choose your background</h1>
{% crispy form form.helper %}

{% endblock content%}

gamelogic/templates/gamelogic/d66_tables.html
{% extends "base.html" %}
{% load static %}
{% block title %}Monolith - Weird Space Stuff{% endblock title %}
{% block content %}
<h1>{{h1}}</h1>

<table class="table">
    <thead>
        <th>d66</th>
        <th></th>
    </thead>
{% for item in table %}
<tr>
    <th>{{item.number}}</th>
    <td><b>{{item.name}}:</b> {{item.description}}</td>
</tr>
{% endfor %}
</table>
{% endblock content %}

templates/base.html
<!DOCTYPE html>
<html lang="en">

<head>

    <!-- boostrap CSS -->

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!--<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/css/bootstrap.min.css" integrity="sha384-xOolHFLEh07PJGoPkLv1IbcEPTNtaed2xpHsD9ESMhqIYd0nLMwNLD69Npy4HI+N" crossorigin="anonymous">
    -->
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@forevolve/bootstrap-dark@1.0.0/dist/css/bootstrap-dark.min.css" />

    {% load static %}
    <link rel="stylesheet" href="{% static 'styles.css' %}">
    <title>{% block title %}{% endblock %}</title>
    <link rel="icon"
        href="data:image/svg+xml,<svg xmlns=%22http://www.w3.org/2000/svg%22 viewBox=%220 0 100 100%22><text y=%22.9em%22 font-size=%2290%22>✒️</text></svg>">

</head>

<body>
<header>

    {% block navbar %}


    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <!--new nav here-->
     <a class="navbar-brand" href="/">Base</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="navbarNavDropdown">
    <ul class="navbar-nav mr-auto">
     <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Characters
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
          <a class="dropdown-item" href="{% url 'chargen:generate_character' %}">Randomize everything</a>
          <a class="dropdown-item" href="{% url 'chargen:generate_with_background' %}">Choose background</a>
          <a class="dropdown-item" href="#">Something else here</a>
        </div>
      </li>
       <li class="nav-item dropdown">
        <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
          Weird Magic stuff
        </a>
        <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
            <a class="dropdown-item" href="#">Spells</a>

        </div>
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
            Procedures
          </a>
          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
              <a class="dropdown-item" href="#">Dungeon events</a>
              <a class="dropdown-item" href="#">Travel events</a>
              <a class="dropdown-item" href="#">Exploration events</a>

          </div>
      </li>

      <!--
      <li class="nav-item">
        <a class="nav-link" href="#">Features</a>
      </li>

        <li class="nav-item">
        <a class="nav-link" href="#">Pricing</a>
      </li>-->

    </ul>
    <ul class="navbar-nav">
      <li class="nav-item">
          <a class="nav-link" href="{% url 'admin:index' %}">Admin</a>
      </li>
      {% if request.user.is_authenticated %}
      <li class="nav-item">
        <a class="nav-link" href="{% url 'admin:logout' %}">Déconnexion</a>
    </li>
    {% endif %}
    </ul>
  </div>
    </nav>

</header>

    {% endblock %}
    <main role="main" class="container">

    {% block messages %}
        {% if messages %}
                {% for message in messages %}
                <div {% if message.tags %} class="alert alert-{{ message.tags }}"{% endif %} role="alert">{{ message }}</div>
                {% endfor %}

        {% endif %}
    {% endblock %}

        {% block content %}{% endblock %}

    </main>

    <!-- Footer -->

       <footer class="footer">

      <nav class="navbar navbar-dark bg-dark">
        <span class="text-muted"><a href="https://www.electrumarchive.com/" target="_blank">The Electrum Archive</a> was written by Emiel Boven.
        </span>
        </nav>

    </footer>
    <!-- Footer -->
    <!-- Jquery and Popper-->
    <script src="https://cdn.jsdelivr.net/npm/jquery@3.5.1/dist/jquery.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>

    <!-- Bootstrap JS -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@4.6.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-Fy6S3B9q64WdZWQUiU+q4/2Lc9npb8tCaSX9FK7E8HnRr0Jz8D6OP9dO5Vg3Q9ct" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load static %}
{% block title %}The Electrum Archive Seer assistant{% endblock title %}
{% block content %}
<h1>Welcome to the Electrum Archive Seer assistant</h1>

<p>The Electrum Archive is a science-fantasy roleplaying game by Emiel Boven & Ava Islam</p>



<p><a target="blank" href="https://www.lulu.com/shop/adam-hensley/monolith/paperback/product-9gpmgz.html?q=monolith&page=1&pageSize=4">Buy a Print Copy from Lulu ( $7.86 + shipping; Price is at-cost, meaning Adam doesn't make a profit.)</a>
</p>

<p>This tool is developped independently from the game, and is provided "as is".</p>
{% endblock content %}